default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  username: postgres
  password: 

development:
  <<: *default
  database: photos_development

test:
  <<: *default
  database: photos_test

#production:
#  <<: *default
#  database: db/production.sqlite3
